cc_binary(
    target_bases = [ 'mmcomm', ],
    name = 'bind_test_1',
    srcs = [ 
        'bind_test_1.cpp',
    ],  
    deps = [ 
      '//mm3rd/boost-1.55:boost_program_options',
      '//mm3rd/boost-1.55:boost_thread',
      '//mm3rd/boost-1.55:boost_system',
    ],  
    extra_cppflags = [ 
        '-Wall',
        '-Werror',
    ]   
)
cc_binary(
    target_bases = [ 'mmcomm', ],
    name = 'function_1',
    srcs = [ 
        'function_1.cpp',
    ],  
    deps = [ 
      '//mm3rd/boost-1.55:boost_program_options',
      '//mm3rd/boost-1.55:boost_thread',
      '//mm3rd/boost-1.55:boost_system',
    ],  
    extra_cppflags = [ 
        '-Wall',
        '-Werror',
    ]   
)
cc_binary(
    target_bases = [ 'mmcomm', ],
    name = 'string_1',
    srcs = [ 
        'string_1.cpp',
    ],  
    deps = [ 
      '//mm3rd/boost-1.55:boost_program_options',
      '//mm3rd/boost-1.55:boost_thread',
      '//mm3rd/boost-1.55:boost_system',
    ],  
    extra_cppflags = [ 
        '-Wall',
        '-Werror',
    ]   
)
cc_binary(
    target_bases = [ 'mmcomm', ],
    name = 'timer_1',
    srcs = [ 
        'timer_1.cpp',
    ],  
    deps = [ 
      '//mm3rd/boost-1.55:boost_program_options',
    ],  
    extra_cppflags = [ 
        '-Wall',
        '-Werror',
    ]   
)
